services:
  localstack:
    container_name: event-service-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./docker-config/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  data-claim-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: data-claim-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./docker-config/wiremock/mappings/data-claims-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8190:8080"
  fee-scheme-platform-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: fee-scheme-platform-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./docker-config/wiremock/mappings/fee-scheme-platform-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8191:8080"
  provider-details-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: provider-details-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./docker-config/wiremock/mappings/provider-details-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8192:8080"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"