services:
  event-service:
    container_name: data-claims-event-service-app
    profiles:
      - application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_PACKAGE_USER=${GIT_PACKAGE_USER}
        - GIT_PACKAGE_KEY=${GIT_PACKAGE_KEY}
    ports:
      - "8091:8091"
      - "8095:8095"
    environment:
      - CLAIMS_API_HOSTNAME=http://host.docker.internal:8080
      - CLAIMS_API_ACCESS_TOKEN=f67f968e-b479-4e61-b66e-f57984931e56
      - BULK_CLAIM_QUEUE_NAME=claims-api-queue
      - PROVIDER_DETAILS_API_HOSTNAME=${PROVIDER_DETAILS_API_HOSTNAME}
      - PROVIDER_DETAILS_API_ACCESS_TOKEN=${PROVIDER_DETAILS_API_ACCESS_TOKEN}
      - FEE_SCHEME_PLATFORM_API_URL=${FEE_SCHEME_PLATFORM_API_URL}
      - FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN=${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN}
      - SUBMISSION_VALIDATION_MINIMUM_PERIOD=JAN-1600
      - SPRING_CLOUD_AWS_REGION_STATIC=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy-access-key
      - AWS_SECRET_ACCESS_KEY=dummy-access-key
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SPRING_CLOUD_AWS_SQS_ENDPOINT=http://localstack:4566
      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY=dummy-access-key
      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY=dummy-access-key
    depends_on:
      - localstack

  localstack:
    container_name: event-service-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./docker-scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  data-claim-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: data-claim-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./wiremock/mappings/data-claims-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8190:8080"
  fee-scheme-platform-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: fee-scheme-platform-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./wiremock/mappings/fee-scheme-platform-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8191:8080"
  provider-details-api-wiremock:
    image: wiremock/wiremock:latest
    container_name: provider-details-api-wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./wiremock/mappings/provider-details-api:/home/wiremock/mappings
    restart: always
    ports:
      - "8192:8080"