laa:
  bulk-claim-queue:
    name: test-queue-name
spring:
  cloud:
    aws:
      region:
        static: us-east-1

resilience4j.retry:
  instances:
    pdaRetry:
      maxAttempts: 3
      waitDuration: 500ms
      retry-exceptions:
        - java.lang.RuntimeException

resilience4j.ratelimiter:
  instances:
    pdaRateLimiterPerSecond:
      limitForPeriod: 1000
      limitRefreshPeriod: 1s
      timeoutDuration: 0
    pdaRateLimiterPerMinute:
      limitForPeriod: 1000
      limitRefreshPeriod: 1s
      timeoutDuration: 0
