# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      integration_test_task: "integrationTest"
      create_tag: 'true'
      github_bot_username: 'laa-ccms-caab-service'
      junit_results_path: 'data-claims-event-service/build/test-results'
      junit_report_path: 'data-claims-event-service/build/reports/tests'
      checkstyle_report_path: 'data-claims-event-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'data-claims-event-service/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      aws_region: ${{ vars.AWS_REGION }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'

  pact-test:
    needs: [ build ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/pact-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      pacticipant_name: "laa-data-claims-event-service"
      pact_test_task: "pactTest"
      publish_pact_results: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}