name: Deploy main

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  assemble:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      build_command: 'assemble'
      publish_package: 'false'
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      aws_region: ${{ vars.AWS_REGION }}

  pact-test:
    needs: [ assemble ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/pact-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      pacticipant_name: "laa-data-claims-event-service"
      pact_test_task: "pactTest"
      publish_pact_results: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      pact_broker_url: ${{ secrets.PACT_BROKER_URL }}
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

  ecr-publish-image:
    needs: [ assemble ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      jar_subproject: 'data-claims-event-service'
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.assemble.outputs.published_artifact_version) }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-uat:
    needs:
      - ecr-publish-image
      - pact-test
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: uat
      deployment_name: uat
      claim_api_environment_name: main
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets: inherit

  deploy-staging:
    needs:
      - ecr-publish-image
      - pact-test
      - deploy-uat
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: staging
      deployment_name: stg
      claim_api_environment_name: stg
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets: inherit

  deploy-production:
    needs:
      - ecr-publish-image
      - pact-test
      - deploy-staging
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: production
      deployment_name: prod
      claim_api_environment_name: prod
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets: inherit
